#!/usr/bin/env python
"""
用途说明
--------
本脚本用于处理 GPUMD 的 EMD/Green-Kubo 热导率计算结果，适合以下场景：
1. 当前目录下存在多个独立重复计算文件夹，例如 `fold1`、`fold2` ... `fold9`。
2. 每个文件夹中都包含由 `compute_hac` 产生的 `hac.out` 文件。
3. 需要提取 z 方向热流自相关函数和 z 方向运行热导率，并判断 `kappa_z(t)` 是否出现平台、是否接近收敛。

脚本功能
--------
本脚本会自动：
1. 搜索 `fold*` 目录中的 `hac.out` 文件。
2. 读取 GPUMD `hac.out` 中的时间列 `t`、z 方向 HAC 列 `jzjz` 和 z 方向运行热导率列 `kz`。
3. 将多个独立运行的数据做平均，并计算标准误 `SEM`。
4. 输出 4 张诊断图和 1 张汇总图，帮助判断 z 方向热导率是否收敛。
5. 导出平均后的 `kappa_z(t)` 数据文件。

输出内容
--------
默认会在 `emd_kappa_output` 文件夹下生成：
1. `emd_kappa_z.dat`
   保存三列数据：时间 `t(ps)`、平均热导率 `kz_mean(W/m/K)`、标准误 `kz_sem(W/m/K)`。
2. `emd_kappa_z_hac.png`
   z 方向归一化热流自相关函数。
3. `emd_kappa_z_runs.png`
   各独立运行的 `kappa_z(t)` 曲线和平均曲线。
4. `emd_kappa_z_mean_sem.png`
   平均 `kappa_z(t)` 曲线及 `SEM` 阴影带。
5. `emd_kappa_z_zoom.png`
   晚时间窗口放大图，并标出平台区间。
6. `emd_kappa_z_summary.png`
   以上 4 个面板组成的汇总图。

基本用法
--------
在脚本所在目录运行：

    python emd_kappa.py

常用参数示例
------------
1. 指定输出目录：

    python emd_kappa.py --output-dir my_results

2. 指定平台区间，例如使用 150 到 400 ps 作为平台判断窗口：

    python emd_kappa.py --plateau-start 150 --plateau-end 400

3. 指定晚时间放大图起点：

    python emd_kappa.py --zoom-start 200

4. 如果文件夹名不是 `fold*`，可以改搜索模式：

    python emd_kappa.py --pattern "run*"

使用前提
--------
1. 需要安装 `numpy` 和 `matplotlib`。
2. 各个 `hac.out` 的时间网格必须一致，否则脚本会报错。
3. 当前脚本默认采用 GPUMD `hac.out` 的列定义：
   - 第 1 列：时间 `t`
   - 第 6 列：`jzjz`
   - 第 11 列：`kz`

适用目的
--------
如果你想回答“z 方向热导率是否收敛”这个问题，重点查看：
1. `emd_kappa_z_runs.png`
2. `emd_kappa_z_mean_sem.png`
3. `emd_kappa_z_zoom.png`

其中 HAC 图主要用于判断相关函数是否已经衰减到噪声区，真正判断平台与收敛，仍应以
`kappa_z(t)` 曲线为主。
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np


TIME_COLUMN = 0
JZJZ_COLUMN = 5
KZ_COLUMN = 10


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read fold*/hac.out files generated by GPUMD compute_hac, "
            "average the z-axis running thermal conductivity, and plot convergence diagnostics."
        )
    )
    parser.add_argument(
        "--pattern",
        default="fold*",
        help="Glob pattern for run folders (default: %(default)s).",
    )
    parser.add_argument(
        "--hac-name",
        default="hac.out",
        help="Name of the GPUMD EMD output file inside each folder (default: %(default)s).",
    )
    parser.add_argument(
        "--output-prefix",
        default="emd_kappa_z",
        help="Prefix for generated figure and data files (default: %(default)s).",
    )
    parser.add_argument(
        "--output-dir",
        default="emd_kappa_output",
        help="Directory used to save figures and data files (default: %(default)s).",
    )
    parser.add_argument(
        "--title",
        default="EMD z-axis thermal conductivity convergence",
        help="Title used in the summary figure.",
    )
    parser.add_argument(
        "--zoom-start",
        type=float,
        default=100.0,
        help="Start time in ps for the late-time zoom panel (default: %(default)s).",
    )
    parser.add_argument(
        "--plateau-start",
        type=float,
        default=100.0,
        help="Start time in ps for the plateau estimate (default: %(default)s).",
    )
    parser.add_argument(
        "--plateau-end",
        type=float,
        default=300.0,
        help="End time in ps for the plateau estimate (default: %(default)s).",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=300,
        help="Figure DPI (default: %(default)s).",
    )
    return parser.parse_args()


def natural_key(path: Path) -> tuple[int, str]:
    suffix = path.name[4:] if path.name.startswith("fold") else path.name
    try:
        return (int(suffix), path.name)
    except ValueError:
        return (10**9, path.name)


def load_runs(
    base_dir: Path, pattern: str, hac_name: str
) -> tuple[np.ndarray, list[str], np.ndarray, np.ndarray]:
    run_dirs = sorted(
        [path for path in base_dir.glob(pattern) if path.is_dir()],
        key=natural_key,
    )
    if not run_dirs:
        raise FileNotFoundError(f"No folders matched pattern {pattern!r} under {base_dir}.")

    labels: list[str] = []
    jzjz_series: list[np.ndarray] = []
    kz_series: list[np.ndarray] = []
    time_grid: np.ndarray | None = None

    for run_dir in run_dirs:
        hac_path = run_dir / hac_name
        if not hac_path.is_file():
            continue

        hac = np.loadtxt(hac_path)
        if hac.ndim != 2 or hac.shape[1] < KZ_COLUMN + 1:
            raise ValueError(
                f"{hac_path} must have at least {KZ_COLUMN + 1} columns, got shape {hac.shape}."
            )

        run_time = hac[:, TIME_COLUMN]
        run_jzjz = hac[:, JZJZ_COLUMN]
        run_kz = hac[:, KZ_COLUMN]

        if time_grid is None:
            time_grid = run_time
        elif run_time.shape != time_grid.shape or not np.allclose(run_time, time_grid):
            raise ValueError(f"Time grid in {hac_path} does not match the other runs.")

        labels.append(run_dir.name)
        jzjz_series.append(run_jzjz)
        kz_series.append(run_kz)

    if time_grid is None or not kz_series:
        raise FileNotFoundError(f"No {hac_name!r} files were found in folders matched by {pattern!r}.")

    return time_grid, labels, np.vstack(jzjz_series), np.vstack(kz_series)


def compute_mean_sem(series: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    mean = series.mean(axis=0)
    sem = (
        series.std(axis=0, ddof=1) / np.sqrt(series.shape[0])
        if series.shape[0] > 1
        else np.zeros_like(mean)
    )
    return mean, sem


def normalize_hac(jzjz_runs: np.ndarray) -> np.ndarray:
    maxima = jzjz_runs.max(axis=1)
    maxima[maxima == 0.0] = 1.0
    return jzjz_runs / maxima[:, None]


def configure_axes(ax: plt.Axes) -> None:
    ax.tick_params(which="major", length=7, width=1.8, direction="in", top=True, right=True)
    ax.tick_params(which="minor", length=4, width=1.4, direction="in", top=True, right=True)


def save_average_data(path: Path, time_grid: np.ndarray, kz_runs: np.ndarray) -> None:
    kz_mean, kz_sem = compute_mean_sem(kz_runs)
    output = np.column_stack((time_grid, kz_mean, kz_sem))
    header = "t_ps kz_mean_W_mK kz_sem_W_mK"
    np.savetxt(path, output, header=header, fmt="%.8f")


def plot_normalized_hac(
    ax: plt.Axes, time_grid: np.ndarray, jzjz_runs: np.ndarray, labels: list[str]
) -> None:
    jzjz_norm = normalize_hac(jzjz_runs)
    jzjz_mean = jzjz_norm.mean(axis=0)

    for label, series in zip(labels, jzjz_norm):
        ax.loglog(time_grid, series, color="0.80", linewidth=1.0, alpha=0.8, label=label)
    ax.loglog(time_grid, jzjz_mean, color="C3", linewidth=2.6, label="mean")

    ax.set_xlabel("Correlation Time (ps)")
    ax.set_ylabel("Normalized z-HAC")
    ax.set_title("(a) Normalized $j_zj_z$")
    ax.set_xlim(time_grid[0], time_grid[-1])
    ax.set_ylim(1.0e-4, 1.2)
    configure_axes(ax)


def plot_kz_runs(
    ax: plt.Axes, time_grid: np.ndarray, kz_runs: np.ndarray, labels: list[str]
) -> tuple[np.ndarray, np.ndarray]:
    kz_mean, kz_sem = compute_mean_sem(kz_runs)

    for label, kz in zip(labels, kz_runs):
        ax.plot(time_grid, kz, color="0.75", linewidth=1.1, alpha=0.9, label=label)
    ax.plot(time_grid, kz_mean, color="C0", linewidth=2.8, label="mean")

    ax.set_xlabel("Correlation Time (ps)")
    ax.set_ylabel(r"$\kappa_z(t)$ (W/m/K)")
    ax.set_title("(b) Individual and mean $\\kappa_z$")
    ax.set_xlim(time_grid[0], time_grid[-1])
    configure_axes(ax)
    return kz_mean, kz_sem


def plot_kz_sem(ax: plt.Axes, time_grid: np.ndarray, kz_runs: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    kz_mean, kz_sem = compute_mean_sem(kz_runs)

    ax.fill_between(
        time_grid,
        kz_mean - kz_sem,
        kz_mean + kz_sem,
        color="C0",
        alpha=0.20,
        linewidth=0,
        label="mean +/- sem",
    )
    ax.plot(time_grid, kz_mean, color="C0", linewidth=2.8, label="mean")

    ax.set_xlabel("Correlation Time (ps)")
    ax.set_ylabel(r"$\kappa_z(t)$ (W/m/K)")
    ax.set_title("(c) Mean $\\kappa_z$ with SEM")
    ax.set_xlim(time_grid[0], time_grid[-1])
    configure_axes(ax)
    return kz_mean, kz_sem


def plot_kz_zoom(
    ax: plt.Axes,
    time_grid: np.ndarray,
    kz_runs: np.ndarray,
    zoom_start: float,
    plateau_start: float,
    plateau_end: float,
) -> tuple[float, float]:
    kz_mean, kz_sem = compute_mean_sem(kz_runs)
    mask_zoom = time_grid >= zoom_start
    if not np.any(mask_zoom):
        raise ValueError(f"No time points are >= zoom_start={zoom_start}.")

    mask_plateau = (time_grid >= plateau_start) & (time_grid <= plateau_end)
    if not np.any(mask_plateau):
        raise ValueError(
            f"No time points fall inside plateau window [{plateau_start}, {plateau_end}] ps."
        )

    plateau_runs = kz_runs[:, mask_plateau].mean(axis=1)
    plateau_mean = plateau_runs.mean()
    plateau_sem = (
        plateau_runs.std(ddof=1) / np.sqrt(plateau_runs.shape[0])
        if plateau_runs.shape[0] > 1
        else 0.0
    )
    y_margin = max(50.0, 0.08 * (kz_mean[mask_zoom].max() - kz_mean[mask_zoom].min() + 1.0))

    ax.fill_between(
        time_grid[mask_zoom],
        (kz_mean - kz_sem)[mask_zoom],
        (kz_mean + kz_sem)[mask_zoom],
        color="C0",
        alpha=0.20,
        linewidth=0,
    )
    ax.plot(time_grid[mask_zoom], kz_mean[mask_zoom], color="C0", linewidth=2.8, label="mean")
    ax.axhline(
        plateau_mean,
        color="k",
        linestyle="--",
        linewidth=1.6,
        label=f"plateau {plateau_start:.0f}-{plateau_end:.0f} ps",
    )
    ax.axvspan(plateau_start, plateau_end, color="0.85", alpha=0.5, linewidth=0)

    ax.set_xlabel("Correlation Time (ps)")
    ax.set_ylabel(r"$\kappa_z(t)$ (W/m/K)")
    ax.set_title("(d) Late-time zoom and plateau guide")
    ax.set_xlim(time_grid[mask_zoom][0], time_grid[mask_zoom][-1])
    ax.set_ylim(kz_mean[mask_zoom].min() - y_margin, kz_mean[mask_zoom].max() + y_margin)
    configure_axes(ax)
    return plateau_mean, plateau_sem


def save_single_panel(fig: plt.Figure, path: Path, dpi: int) -> None:
    fig.tight_layout()
    fig.savefig(path, dpi=dpi)
    plt.close(fig)


def build_output_paths(output_dir: Path, prefix: str) -> dict[str, Path]:
    return {
        "data": output_dir / f"{prefix}.dat",
        "summary": output_dir / f"{prefix}_summary.png",
        "hac": output_dir / f"{prefix}_hac.png",
        "runs": output_dir / f"{prefix}_runs.png",
        "mean_sem": output_dir / f"{prefix}_mean_sem.png",
        "zoom": output_dir / f"{prefix}_zoom.png",
    }


def build_figures(
    output_paths: dict[str, Path],
    time_grid: np.ndarray,
    labels: list[str],
    jzjz_runs: np.ndarray,
    kz_runs: np.ndarray,
    title: str,
    zoom_start: float,
    plateau_start: float,
    plateau_end: float,
    dpi: int,
) -> tuple[np.ndarray, np.ndarray, float, float]:
    plt.rcParams.update(
        {
            "font.size": 13,
            "axes.linewidth": 1.8,
        }
    )

    fig_summary, axes = plt.subplots(2, 2, figsize=(12.5, 10.0))
    plot_normalized_hac(axes[0, 0], time_grid, jzjz_runs, labels)
    kz_mean, kz_sem = plot_kz_runs(axes[0, 1], time_grid, kz_runs, labels)
    plot_kz_sem(axes[1, 0], time_grid, kz_runs)
    plateau_mean, plateau_sem = plot_kz_zoom(
        axes[1, 1], time_grid, kz_runs, zoom_start, plateau_start, plateau_end
    )
    fig_summary.suptitle(title, y=0.98)
    fig_summary.tight_layout(rect=(0.0, 0.0, 1.0, 0.97))
    fig_summary.savefig(output_paths["summary"], dpi=dpi)
    plt.close(fig_summary)

    fig_a, ax_a = plt.subplots(figsize=(7.5, 5.6))
    plot_normalized_hac(ax_a, time_grid, jzjz_runs, labels)
    save_single_panel(fig_a, output_paths["hac"], dpi)

    fig_b, ax_b = plt.subplots(figsize=(7.5, 5.6))
    plot_kz_runs(ax_b, time_grid, kz_runs, labels)
    save_single_panel(fig_b, output_paths["runs"], dpi)

    fig_c, ax_c = plt.subplots(figsize=(7.5, 5.6))
    plot_kz_sem(ax_c, time_grid, kz_runs)
    save_single_panel(fig_c, output_paths["mean_sem"], dpi)

    fig_d, ax_d = plt.subplots(figsize=(7.5, 5.6))
    plot_kz_zoom(ax_d, time_grid, kz_runs, zoom_start, plateau_start, plateau_end)
    save_single_panel(fig_d, output_paths["zoom"], dpi)

    return kz_mean, kz_sem, plateau_mean, plateau_sem


def main() -> None:
    args = parse_args()
    base_dir = Path.cwd()
    output_dir = base_dir / args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    output_paths = build_output_paths(output_dir, args.output_prefix)

    time_grid, labels, jzjz_runs, kz_runs = load_runs(base_dir, args.pattern, args.hac_name)
    save_average_data(output_paths["data"], time_grid, kz_runs)
    kz_mean, kz_sem, plateau_mean, plateau_sem = build_figures(
        output_paths,
        time_grid,
        labels,
        jzjz_runs,
        kz_runs,
        args.title,
        args.zoom_start,
        args.plateau_start,
        args.plateau_end,
        args.dpi,
    )

    print(f"Loaded {len(labels)} runs: {', '.join(labels)}")
    print(f"Saved averaged data to {output_paths['data'].resolve()}")
    print(f"Saved summary figure to {output_paths['summary'].resolve()}")
    print(f"Saved panel (a) to {output_paths['hac'].resolve()}")
    print(f"Saved panel (b) to {output_paths['runs'].resolve()}")
    print(f"Saved panel (c) to {output_paths['mean_sem'].resolve()}")
    print(f"Saved panel (d) to {output_paths['zoom'].resolve()}")
    print(f"Final-point mean kz = {kz_mean[-1]:.6f} W/m/K")
    print(f"Final-point sem  kz = {kz_sem[-1]:.6f} W/m/K")
    print(
        "Plateau-guide mean kz "
        f"({args.plateau_start:.0f}-{args.plateau_end:.0f} ps) = {plateau_mean:.6f} W/m/K"
    )
    print(
        "Plateau-guide sem  kz "
        f"({args.plateau_start:.0f}-{args.plateau_end:.0f} ps) = {plateau_sem:.6f} W/m/K"
    )


if __name__ == "__main__":
    main()
